/* shimdb curated impl: CoreMedia "Fig*" private symbols (removed on modern
 * macOS) forwarded to their byte-identical public CM* equivalents. The Fig
 * API IS the CoreMedia API pre-rename (Apple shipped public CoreMedia in 10.7
 * by mechanically renaming Fig*->CM*); the C structs/enums/CFTypes are
 * identical, so each thunk is a register-preserving tail JMP to the CM symbol
 * -- signature-agnostic and ABI-exact for any arg/return shape (incl. by-value
 * CMTime and struct-return-in-rdi). Generated; one entry per forwarded symbol.
 */
__asm__(
"  .text\n"
"  .globl _FigAudioFormatDescriptionCreate\n"
"_FigAudioFormatDescriptionCreate:\n"
"  jmp *_CMAudioFormatDescriptionCreate@GOTPCREL(%rip)\n"
"  .globl _FigAudioFormatDescriptionGetChannelLayout\n"
"_FigAudioFormatDescriptionGetChannelLayout:\n"
"  jmp *_CMAudioFormatDescriptionGetChannelLayout@GOTPCREL(%rip)\n"
"  .globl _FigAudioFormatDescriptionGetFormatList\n"
"_FigAudioFormatDescriptionGetFormatList:\n"
"  jmp *_CMAudioFormatDescriptionGetFormatList@GOTPCREL(%rip)\n"
"  .globl _FigAudioFormatDescriptionGetMagicCookie\n"
"_FigAudioFormatDescriptionGetMagicCookie:\n"
"  jmp *_CMAudioFormatDescriptionGetMagicCookie@GOTPCREL(%rip)\n"
"  .globl _FigAudioFormatDescriptionGetStreamBasicDescription\n"
"_FigAudioFormatDescriptionGetStreamBasicDescription:\n"
"  jmp *_CMAudioFormatDescriptionGetStreamBasicDescription@GOTPCREL(%rip)\n"
"  .globl _FigBlockBufferCopyDataBytes\n"
"_FigBlockBufferCopyDataBytes:\n"
"  jmp *_CMBlockBufferCopyDataBytes@GOTPCREL(%rip)\n"
"  .globl _FigBlockBufferCreateWithMemoryBlock\n"
"_FigBlockBufferCreateWithMemoryBlock:\n"
"  jmp *_CMBlockBufferCreateWithMemoryBlock@GOTPCREL(%rip)\n"
"  .globl _FigBlockBufferGetDataLength\n"
"_FigBlockBufferGetDataLength:\n"
"  jmp *_CMBlockBufferGetDataLength@GOTPCREL(%rip)\n"
"  .globl _FigBlockBufferGetDataPointer\n"
"_FigBlockBufferGetDataPointer:\n"
"  jmp *_CMBlockBufferGetDataPointer@GOTPCREL(%rip)\n"
"  .globl _FigBlockBufferIsRangeContiguous\n"
"_FigBlockBufferIsRangeContiguous:\n"
"  jmp *_CMBlockBufferIsRangeContiguous@GOTPCREL(%rip)\n"
"  .globl _FigBufferQueueCreate\n"
"_FigBufferQueueCreate:\n"
"  jmp *_CMBufferQueueCreate@GOTPCREL(%rip)\n"
"  .globl _FigBufferQueueDequeueAndRetain\n"
"_FigBufferQueueDequeueAndRetain:\n"
"  jmp *_CMBufferQueueDequeueAndRetain@GOTPCREL(%rip)\n"
"  .globl _FigBufferQueueEnqueue\n"
"_FigBufferQueueEnqueue:\n"
"  jmp *_CMBufferQueueEnqueue@GOTPCREL(%rip)\n"
"  .globl _FigBufferQueueGetBufferCount\n"
"_FigBufferQueueGetBufferCount:\n"
"  jmp *_CMBufferQueueGetBufferCount@GOTPCREL(%rip)\n"
"  .globl _FigBufferQueueGetCallbacksForUnsortedSampleBuffers\n"
"_FigBufferQueueGetCallbacksForUnsortedSampleBuffers:\n"
"  jmp *_CMBufferQueueGetCallbacksForUnsortedSampleBuffers@GOTPCREL(%rip)\n"
"  .globl _FigBufferQueueGetHead\n"
"_FigBufferQueueGetHead:\n"
"  jmp *_CMBufferQueueGetHead@GOTPCREL(%rip)\n"
"  .globl _FigBufferQueueInstallTriggerWithIntegerThreshold\n"
"_FigBufferQueueInstallTriggerWithIntegerThreshold:\n"
"  jmp *_CMBufferQueueInstallTriggerWithIntegerThreshold@GOTPCREL(%rip)\n"
"  .globl _FigBufferQueueIsAtEndOfData\n"
"_FigBufferQueueIsAtEndOfData:\n"
"  jmp *_CMBufferQueueIsAtEndOfData@GOTPCREL(%rip)\n"
"  .globl _FigBufferQueueIsEmpty\n"
"_FigBufferQueueIsEmpty:\n"
"  jmp *_CMBufferQueueIsEmpty@GOTPCREL(%rip)\n"
"  .globl _FigBufferQueueMarkEndOfData\n"
"_FigBufferQueueMarkEndOfData:\n"
"  jmp *_CMBufferQueueMarkEndOfData@GOTPCREL(%rip)\n"
"  .globl _FigByteStreamBaseGetTypeID\n"
"_FigByteStreamBaseGetTypeID:\n"
"  jmp *_CMByteStreamBaseGetTypeID@GOTPCREL(%rip)\n"
"  .globl _FigCopyDictionaryOfAttachments\n"
"_FigCopyDictionaryOfAttachments:\n"
"  jmp *_CMCopyDictionaryOfAttachments@GOTPCREL(%rip)\n"
"  .globl _FigFormatDescriptionCreate\n"
"_FigFormatDescriptionCreate:\n"
"  jmp *_CMFormatDescriptionCreate@GOTPCREL(%rip)\n"
"  .globl _FigFormatDescriptionGetExtension\n"
"_FigFormatDescriptionGetExtension:\n"
"  jmp *_CMFormatDescriptionGetExtension@GOTPCREL(%rip)\n"
"  .globl _FigFormatDescriptionGetExtensions\n"
"_FigFormatDescriptionGetExtensions:\n"
"  jmp *_CMFormatDescriptionGetExtensions@GOTPCREL(%rip)\n"
"  .globl _FigFormatDescriptionGetMediaSubType\n"
"_FigFormatDescriptionGetMediaSubType:\n"
"  jmp *_CMFormatDescriptionGetMediaSubType@GOTPCREL(%rip)\n"
"  .globl _FigFormatDescriptionGetMediaType\n"
"_FigFormatDescriptionGetMediaType:\n"
"  jmp *_CMFormatDescriptionGetMediaType@GOTPCREL(%rip)\n"
"  .globl _FigGetAttachment\n"
"_FigGetAttachment:\n"
"  jmp *_CMGetAttachment@GOTPCREL(%rip)\n"
"  .globl _FigNotificationCenterAddListener\n"
"_FigNotificationCenterAddListener:\n"
"  jmp *_CMNotificationCenterAddListener@GOTPCREL(%rip)\n"
"  .globl _FigNotificationCenterPostNotification\n"
"_FigNotificationCenterPostNotification:\n"
"  jmp *_CMNotificationCenterPostNotification@GOTPCREL(%rip)\n"
"  .globl _FigNotificationCenterRemoveListener\n"
"_FigNotificationCenterRemoveListener:\n"
"  jmp *_CMNotificationCenterRemoveListener@GOTPCREL(%rip)\n"
"  .globl _FigRemoveAttachment\n"
"_FigRemoveAttachment:\n"
"  jmp *_CMRemoveAttachment@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferCreate\n"
"_FigSampleBufferCreate:\n"
"  jmp *_CMSampleBufferCreate@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferCreateCopyWithNewTiming\n"
"_FigSampleBufferCreateCopyWithNewTiming:\n"
"  jmp *_CMSampleBufferCreateCopyWithNewTiming@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferCreateForImageBuffer\n"
"_FigSampleBufferCreateForImageBuffer:\n"
"  jmp *_CMSampleBufferCreateForImageBuffer@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferGetAudioBufferListWithRetainedBlockBuffer\n"
"_FigSampleBufferGetAudioBufferListWithRetainedBlockBuffer:\n"
"  jmp *_CMSampleBufferGetAudioBufferListWithRetainedBlockBuffer@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferGetAudioStreamPacketDescriptionsPtr\n"
"_FigSampleBufferGetAudioStreamPacketDescriptionsPtr:\n"
"  jmp *_CMSampleBufferGetAudioStreamPacketDescriptionsPtr@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferGetDataBuffer\n"
"_FigSampleBufferGetDataBuffer:\n"
"  jmp *_CMSampleBufferGetDataBuffer@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferGetDuration\n"
"_FigSampleBufferGetDuration:\n"
"  jmp *_CMSampleBufferGetDuration@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferGetFormatDescription\n"
"_FigSampleBufferGetFormatDescription:\n"
"  jmp *_CMSampleBufferGetFormatDescription@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferGetImageBuffer\n"
"_FigSampleBufferGetImageBuffer:\n"
"  jmp *_CMSampleBufferGetImageBuffer@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferGetNumSamples\n"
"_FigSampleBufferGetNumSamples:\n"
"  jmp *_CMSampleBufferGetNumSamples@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferGetOutputDecodeTimeStamp\n"
"_FigSampleBufferGetOutputDecodeTimeStamp:\n"
"  jmp *_CMSampleBufferGetOutputDecodeTimeStamp@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferGetOutputDuration\n"
"_FigSampleBufferGetOutputDuration:\n"
"  jmp *_CMSampleBufferGetOutputDuration@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferGetOutputPresentationTimeStamp\n"
"_FigSampleBufferGetOutputPresentationTimeStamp:\n"
"  jmp *_CMSampleBufferGetOutputPresentationTimeStamp@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferGetSampleAttachmentsArray\n"
"_FigSampleBufferGetSampleAttachmentsArray:\n"
"  jmp *_CMSampleBufferGetSampleAttachmentsArray@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferGetSampleSizeArray\n"
"_FigSampleBufferGetSampleSizeArray:\n"
"  jmp *_CMSampleBufferGetSampleSizeArray@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferGetSampleTimingInfoArray\n"
"_FigSampleBufferGetSampleTimingInfoArray:\n"
"  jmp *_CMSampleBufferGetSampleTimingInfoArray@GOTPCREL(%rip)\n"
"  .globl _FigSampleBufferSetOutputPresentationTimeStamp\n"
"_FigSampleBufferSetOutputPresentationTimeStamp:\n"
"  jmp *_CMSampleBufferSetOutputPresentationTimeStamp@GOTPCREL(%rip)\n"
"  .globl _FigSetAttachment\n"
"_FigSetAttachment:\n"
"  jmp *_CMSetAttachment@GOTPCREL(%rip)\n"
"  .globl _FigSetAttachments\n"
"_FigSetAttachments:\n"
"  jmp *_CMSetAttachments@GOTPCREL(%rip)\n"
"  .globl _FigTimeAdd\n"
"_FigTimeAdd:\n"
"  jmp *_CMTimeAdd@GOTPCREL(%rip)\n"
"  .globl _FigTimeCompare\n"
"_FigTimeCompare:\n"
"  jmp *_CMTimeCompare@GOTPCREL(%rip)\n"
"  .globl _FigTimeConvertScale\n"
"_FigTimeConvertScale:\n"
"  jmp *_CMTimeConvertScale@GOTPCREL(%rip)\n"
"  .globl _FigTimeCopyAsDictionary\n"
"_FigTimeCopyAsDictionary:\n"
"  jmp *_CMTimeCopyAsDictionary@GOTPCREL(%rip)\n"
"  .globl _FigTimeGetSeconds\n"
"_FigTimeGetSeconds:\n"
"  jmp *_CMTimeGetSeconds@GOTPCREL(%rip)\n"
"  .globl _FigTimeMake\n"
"_FigTimeMake:\n"
"  jmp *_CMTimeMake@GOTPCREL(%rip)\n"
"  .globl _FigTimeMakeFromDictionary\n"
"_FigTimeMakeFromDictionary:\n"
"  jmp *_CMTimeMakeFromDictionary@GOTPCREL(%rip)\n"
"  .globl _FigTimeMultiplyByFloat64\n"
"_FigTimeMultiplyByFloat64:\n"
"  jmp *_CMTimeMultiplyByFloat64@GOTPCREL(%rip)\n"
"  .globl _FigTimeSubtract\n"
"_FigTimeSubtract:\n"
"  jmp *_CMTimeSubtract@GOTPCREL(%rip)\n"
"  .globl _FigVideoFormatDescriptionCreate\n"
"_FigVideoFormatDescriptionCreate:\n"
"  jmp *_CMVideoFormatDescriptionCreate@GOTPCREL(%rip)\n"
"  .globl _FigVideoFormatDescriptionGetExtensionKeysCommonWithImageBuffers\n"
"_FigVideoFormatDescriptionGetExtensionKeysCommonWithImageBuffers:\n"
"  jmp *_CMVideoFormatDescriptionGetExtensionKeysCommonWithImageBuffers@GOTPCREL(%rip)\n"
"  .globl _FigVideoFormatDescriptionGetPresentationDimensions\n"
"_FigVideoFormatDescriptionGetPresentationDimensions:\n"
"  jmp *_CMVideoFormatDescriptionGetPresentationDimensions@GOTPCREL(%rip)\n"
);
