/* includes_legacy.h — umbrella headers for the LEGACY abigen pass.
 *
 * This file is parsed by a SEPARATE abigen invocation whose -isysroot is the
 * extracted MacOSX10.6 SDK (~/projects/Library/SDKs/MacOSX10.6.sdk), isolated
 * from the modern pass (includes.h). Its job is to give abigen the PROTOTYPES
 * for framework C functions whose HEADERS modern macOS deleted, so it can emit
 * real ABI-marshalling shims for them. See the shimdb legacy expansion.
 *
 * The consider set (abiconv_legacy.syms, generated by
 * src/86x64/shimdb_legacy_considerset.py) is (all 10.6 SDK framework exports)
 * MINUS (symbols the modern pass already shims), so a symbol declared here is
 * only emitted if it is NOT already covered — no cross-pass label collision.
 * Two sub-classes both get a marshalling shim; the `call _sym` resolves at
 * runtime to either the LIVE native function (SURVIVED, header-deleted) or a
 * graceful shimgen/shimdb stub (DELETED). Because the consider set gates
 * emission, this header list can be generous: an umbrella whose symbols are all
 * already shimmed simply contributes nothing.
 *
 * abigen runs this with -x objective-c (some Carbon/QuickTime headers reference
 * NSString etc.). Headers that fail to parse contribute no cursors but do not
 * abort the run (abigen surfaces diagnostics and continues).
 */

/* AGL — OpenGL context API for Carbon (all 79 exports survive on modern macOS
 * but lost their header). The clean first proof: scalars / void* / enums. */
#include <AGL/agl.h>

/* The Carbon umbrella — the bulk of the legacy C API surface. Pulls in
 * CoreServices (CarbonCore: File/Memory/Resource/Thread Manager, OSUtils,
 * Multiprocessing; OSServices), ApplicationServices (ATS, ColorSync, the old
 * QuickDraw CoreGraphics, LaunchServices, PrintCore, QD, SpeechSynthesis,
 * HIServices) and HIToolbox (Window/Menu/Control/Dialog/Event/Appearance
 * Manager). Most of these subsystems are gone or header-stripped on modern
 * macOS; the ones that survive (a lot of CoreServices/HIServices) call live. */
#include <Carbon/Carbon.h>

/* Listed explicitly so their VarDecls/decls are unambiguous even though Carbon
 * re-includes them. Harmless: a function emitted while processing Carbon.h is
 * erased from the consider set, so it is not re-emitted here. */
#include <ApplicationServices/ApplicationServices.h>
#include <CoreServices/CoreServices.h>

/* QuickTime — the classic Movie Toolbox / GraphicsImporter / Media Handler C
 * API. Entirely removed from modern macOS, so almost everything here is the
 * DELETED class (shimgen-backed); the marshalling shim still makes the i386
 * frame correct. Big win for any QuickTime-era media app. */
#include <QuickTime/QuickTime.h>

/* ICADevices / Image Capture — the real camera/scanner C API (ICAGetDeviceList,
 * ICAObjectSendMessage, ...). Modern macOS deleted the header; today these have
 * a hand graceful stub (imagecapture_shim.c). The prototypes here let abigen
 * marshal them correctly. */
#include <ICADevices/ICADevices.h>

/* Security — Keychain Services / SecCertificate / SecTrust C API. Mostly
 * survives on modern macOS but much of it lost its old header form. */
#include <Security/Security.h>

/* AddressBook — the C API (ABAddressBookRef, ABRecordRef, ...). */
#include <AddressBook/AddressBook.h>

/* DiscRecording — burn engine C API. */
#include <DiscRecording/DiscRecording.h>

/* Audio C APIs — games and media apps drive these directly via i386 cdecl.
 * AudioToolbox (AudioQueue/AudioFile/AudioConverter/ExtAudioFile/MusicPlayer),
 * CoreAudio (HAL AudioHardware*, AudioDevice*), AudioUnit (AudioComponent /
 * AudioUnit render), CoreMIDI (MIDIClientCreate/MIDISend/...). Most survive on
 * modern macOS; some entry points lost their old header form. */
#include <AudioToolbox/AudioToolbox.h>
#include <CoreAudio/CoreAudio.h>
#include <AudioUnit/AudioUnit.h>
#include <CoreMIDI/CoreMIDI.h>

/* OpenAL — positional audio for games (alGenSources/alSourcePlay/alBufferData,
 * alcOpenDevice/...). Survives on modern macOS (deprecated). */
#include <OpenAL/al.h>
#include <OpenAL/alc.h>

/* QuickLook — thumbnail/preview C API (QLThumbnailImageCreate, ...). */
#include <QuickLook/QuickLook.h>

/* CoreVideo — CVPixelBuffer / CVDisplayLink / CVImageBuffer C API (video and
 * GL-texture upload paths). */
#include <CoreVideo/CoreVideo.h>

/* DVDPlayback — the DVD Playback Services C API (DVD-player apps). Gone from
 * modern macOS -> DELETED class (shimgen-backed), marshalling shim still made. */
#include <DVDPlayback/DVDPlayback.h>

/* DrawSprocket + GLUT — classic game-era display / GL utility C APIs. Both gone
 * from modern macOS (DELETED), so the marshalling shims pair with shimgen. */
#include <DrawSprocket/DrawSprocket.h>
#include <GLUT/glut.h>

/* Accelerate — vecLib (vDSP signal processing, cblas/LAPACK, vForce) + vImage.
 * Image/signal-heavy legacy apps call these via cdecl; survives on modern macOS.
 * Struct-by-value/complex args are skipped by abigen; the scalar/pointer-array
 * entry points (the bulk) marshal correctly. */
#include <Accelerate/Accelerate.h>

/* IOBluetooth — the C API surface (IOBluetoothDeviceInquiry, ...). Mostly ObjC
 * (skipped), but the C functions that survive get marshalled. */
#include <IOBluetooth/IOBluetooth.h>
